version: '3'

services:
  db:
    image: postgres:11.5
    ports:
      - "5432:5432"
  web:
    image: "${APP_NAME}_${APP_HASH}"
    build:
      context: .
      args:
        TEST: "true"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
